packages:
  - mk
  - pkg/*
  - integ/*

peerDependencyRules:
  ignoreMissing:
    - eslint*
    - typescript
    - webpack

onlyBuiltDependencies:
  - bufferutil
  - classic-level
  - esbuild
  - memif
  - puppeteer
  - unrs-resolver
