allowBuilds:
  bufferutil: true
  classic-level: true
  memif: true
  puppeteer: true
  unrs-resolver: true

blockExoticSubdeps: false

packages:
  - integ/*
  - mk
  - pkg/*

peerDependencyRules:
  ignoreMissing:
    - eslint*
    - typescript
    - webpack

publicHoistPattern:
  - "@types/*"
  - xo

saveWorkspaceProtocol: rolling
