onlyBuiltDependencies:
  - bufferutil
  - classic-level
  - esbuild
  - memif
  - puppeteer
  - unrs-resolver

packages:
  - integ/*
  - mk
  - pkg/*

peerDependencyRules:
  ignoreMissing:
    - eslint*
    - typescript
    - webpack

publicHoistPattern:
  - "@types/*"
  - xo

saveWorkspaceProtocol: rolling
